[package]
name = "rustango"
description = "A Django-inspired ORM for Rust. Facade crate."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
default = ["postgres"]
postgres = ["rustango-sql/postgres"]

[dependencies]
rustango-core    = { workspace = true }
rustango-macros  = { workspace = true }
rustango-query   = { workspace = true }
rustango-sql     = { workspace = true }
rustango-migrate = { workspace = true }

[dev-dependencies]
tokio      = { workspace = true }
chrono     = { workspace = true }
uuid       = { workspace = true }
serde_json = { workspace = true }
